site_name: fleetmaster
repo_url: https://github.com/eelcovv/fleetmaster
site_url: https://eelcovv.github.io/fleetmaster
site_description: A wrapper to run capytaine in batch from the commandline
site_author: Eelco van Vliet
edit_uri: edit/main/docs/
repo_name: eelcovv/fleetmaster
copyright: Maintained by <a href="https://usedave.nl/welcome.html">dave lab</a>.

nav:
  - Home: index.md
  - General: general_description.md
  - Solution Database: database.md
  - Mesh Fitting: fitting.md
  - Modules: modules.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/fleetmaster"]

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    - content.code.mermaid
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eelcovv/fleetmaster
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fleetmaster

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js
  - javascripts/katex.js
