#full Example configuration file for Fleetmaster
#
# This file defines a "scene" with multiple meshes.
# - `base_mesh` is used to define the origin of the database (the center of mass of this mesh).
# - `stl_files` is a list of meshes that should actually be simulated.
#
# In this example:
# 1. `defraction_box.stl` defines the origin but is not simulated itself because it's not in the `stl_files` list.
# 2. `defraction_box_1m.stl` and `defraction_box_2m.stl` are simulated.
#    The `translation` vector for these files is [0, 0, 0] because the geometry in the STL files themselves
#    already has the correct positin. The engine will calculate and store the final transformation
#    relative to the `base_mesh` origin.

# The base mesh is L x W x H = 3 x 2 x 3
base_mesh: "defraction_box_half.stl"
# The origin in the local coordinate system of the base mesh
base_origin: [0, 0.0, 1.5]

output_hdf5_file: defraction_box_half.hdf5
grid_symmetry: true

stl_files:
  - file: "defraction_box_half_1m.stl"
    translation: [0.0, 0.0, -1.0]
    # this puts the cog in the centre at the water level
    cog: [0.0, 0.0, 0.0]
    # This mesh will use the global wave_periods and wave_directions.

  - file: "defraction_box_half_2m.stl"
    translation: [0, 0.0, -2.0]
    # This mesh overrides the global wave_directions with its own specific values.
    wave_directions: [0, 90, 180]
    # if no  cog is given it is at the real cog, i.e. (0, 0, -1) in this caee

wave_periods: [8.0, 10.0, 12.0]
wave_directions: [0, 45, 90, 135, 180]
